"""create initial schema

Revision ID: a40f4ff284f0
Revises: 
Create Date: 2026-05-03 19:12:47.275608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a40f4ff284f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('darija_glossary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('english_term', sa.String(length=100), nullable=False),
    sa.Column('darija_translation', sa.String(length=255), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_darija_glossary_category'), 'darija_glossary', ['category'], unique=False)
    op.create_index(op.f('ix_darija_glossary_english_term'), 'darija_glossary', ['english_term'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rss_url', sa.Text(), nullable=True),
    sa.Column('scraping_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=True)
    op.create_table('raw_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('original_title', sa.Text(), nullable=False),
    sa.Column('original_content', sa.Text(), nullable=False),
    sa.Column('original_excerpt', sa.Text(), nullable=True),
    sa.Column('original_image_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("processing_status IN ('pending','processing','translated','published','failed','rejected')", name='ck_raw_articles_processing_status'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_url')
    )
    op.create_index('idx_raw_articles_processing_status_fetched_at', 'raw_articles', ['processing_status', 'fetched_at'], unique=False)
    op.create_index(op.f('ix_raw_articles_processing_status'), 'raw_articles', ['processing_status'], unique=False)
    op.create_index(op.f('ix_raw_articles_source_id'), 'raw_articles', ['source_id'], unique=False)
    op.create_index(op.f('ix_raw_articles_url_hash'), 'raw_articles', ['url_hash'], unique=True)
    op.create_table('ai_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('raw_article_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raw_article_id'], ['raw_articles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_logs_created_at'), 'ai_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_logs_provider'), 'ai_logs', ['provider'], unique=False)
    op.create_index(op.f('ix_ai_logs_raw_article_id'), 'ai_logs', ['raw_article_id'], unique=False)
    op.create_index(op.f('ix_ai_logs_success'), 'ai_logs', ['success'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_article_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title_darija', sa.Text(), nullable=False),
    sa.Column('excerpt_darija', sa.Text(), nullable=False),
    sa.Column('content_darija', sa.Text(), nullable=False),
    sa.Column('meta_title', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('hero_image_url', sa.Text(), nullable=True),
    sa.Column('hero_image_alt', sa.Text(), nullable=True),
    sa.Column('categories', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('reading_time_minutes', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('views_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raw_article_id'], ['raw_articles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_articles_categories', 'articles', ['categories'], unique=False, postgresql_using='gin')
    op.create_index('idx_articles_is_published_published_at', 'articles', ['is_published', sa.literal_column('published_at DESC')], unique=False)
    op.create_index('idx_articles_tags', 'articles', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_articles_published_at'), 'articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_articles_raw_article_id'), 'articles', ['raw_article_id'], unique=False)
    op.create_index(op.f('ix_articles_slug'), 'articles', ['slug'], unique=True)
    op.create_table('social_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('post_text', sa.Text(), nullable=False),
    sa.Column('external_post_id', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("platform IN ('linkedin','twitter','facebook','instagram')", name='ck_social_posts_platform'),
    sa.CheckConstraint("status IN ('pending','posted','failed')", name='ck_social_posts_status'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_posts_article_id'), 'social_posts', ['article_id'], unique=False)
    op.create_index(op.f('ix_social_posts_platform'), 'social_posts', ['platform'], unique=False)
    op.create_index(op.f('ix_social_posts_status'), 'social_posts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_posts_status'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_platform'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_article_id'), table_name='social_posts')
    op.drop_table('social_posts')
    op.drop_index(op.f('ix_articles_slug'), table_name='articles')
    op.drop_index(op.f('ix_articles_raw_article_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_published_at'), table_name='articles')
    op.drop_index('idx_articles_tags', table_name='articles', postgresql_using='gin')
    op.drop_index('idx_articles_is_published_published_at', table_name='articles')
    op.drop_index('idx_articles_categories', table_name='articles', postgresql_using='gin')
    op.drop_table('articles')
    op.drop_index(op.f('ix_ai_logs_success'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_raw_article_id'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_provider'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_created_at'), table_name='ai_logs')
    op.drop_table('ai_logs')
    op.drop_index(op.f('ix_raw_articles_url_hash'), table_name='raw_articles')
    op.drop_index(op.f('ix_raw_articles_source_id'), table_name='raw_articles')
    op.drop_index(op.f('ix_raw_articles_processing_status'), table_name='raw_articles')
    op.drop_index('idx_raw_articles_processing_status_fetched_at', table_name='raw_articles')
    op.drop_table('raw_articles')
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_table('sources')
    op.drop_index(op.f('ix_darija_glossary_english_term'), table_name='darija_glossary')
    op.drop_index(op.f('ix_darija_glossary_category'), table_name='darija_glossary')
    op.drop_table('darija_glossary')
    # ### end Alembic commands ###
